// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/rtapi_message.proto

#ifndef PROTOBUF_INCLUDED_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto
#define PROTOBUF_INCLUDED_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "machinetalk/protobuf/nanopb.pb.h"
#include "machinetalk/protobuf/value.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto 

namespace protobuf_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto
namespace machinetalk {
class RTAPI_Message;
class RTAPI_MessageDefaultTypeInternal;
extern RTAPI_MessageDefaultTypeInternal _RTAPI_Message_default_instance_;
}  // namespace machinetalk
namespace google {
namespace protobuf {
template<> ::machinetalk::RTAPI_Message* Arena::CreateMaybeMessage<::machinetalk::RTAPI_Message>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace machinetalk {

// ===================================================================

class RTAPI_Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:machinetalk.RTAPI_Message) */ {
 public:
  RTAPI_Message();
  virtual ~RTAPI_Message();

  RTAPI_Message(const RTAPI_Message& from);

  inline RTAPI_Message& operator=(const RTAPI_Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RTAPI_Message(RTAPI_Message&& from) noexcept
    : RTAPI_Message() {
    *this = ::std::move(from);
  }

  inline RTAPI_Message& operator=(RTAPI_Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RTAPI_Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RTAPI_Message* internal_default_instance() {
    return reinterpret_cast<const RTAPI_Message*>(
               &_RTAPI_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RTAPI_Message* other);
  friend void swap(RTAPI_Message& a, RTAPI_Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RTAPI_Message* New() const final {
    return CreateMaybeMessage<RTAPI_Message>(NULL);
  }

  RTAPI_Message* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RTAPI_Message>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RTAPI_Message& from);
  void MergeFrom(const RTAPI_Message& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RTAPI_Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .machinetalk.Value arg = 30 [(.nanopb) = {
  int arg_size() const;
  void clear_arg();
  static const int kArgFieldNumber = 30;
  ::machinetalk::Value* mutable_arg(int index);
  ::google::protobuf::RepeatedPtrField< ::machinetalk::Value >*
      mutable_arg();
  const ::machinetalk::Value& arg(int index) const;
  ::machinetalk::Value* add_arg();
  const ::google::protobuf::RepeatedPtrField< ::machinetalk::Value >&
      arg() const;

  // required string format = 20 [default = "*** uninitialized ***", (.nanopb) = {
  bool has_format() const;
  void clear_format();
  static const int kFormatFieldNumber = 20;
  const ::std::string& format() const;
  void set_format(const ::std::string& value);
  #if LANG_CXX11
  void set_format(::std::string&& value);
  #endif
  void set_format(const char* value);
  void set_format(const char* value, size_t size);
  ::std::string* mutable_format();
  ::std::string* release_format();
  void set_allocated_format(::std::string* format);

  // required int32 msglevel = 10;
  bool has_msglevel() const;
  void clear_msglevel();
  static const int kMsglevelFieldNumber = 10;
  ::google::protobuf::int32 msglevel() const;
  void set_msglevel(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:machinetalk.RTAPI_Message)
 private:
  void set_has_msglevel();
  void clear_has_msglevel();
  void set_has_format();
  void clear_has_format();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::machinetalk::Value > arg_;
  public:
  static ::google::protobuf::internal::ExplicitlyConstructed< ::std::string> _i_give_permission_to_break_this_code_default_format_;
  private:
  ::google::protobuf::internal::ArenaStringPtr format_;
  ::google::protobuf::int32 msglevel_;
  friend struct ::protobuf_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RTAPI_Message

// required int32 msglevel = 10;
inline bool RTAPI_Message::has_msglevel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RTAPI_Message::set_has_msglevel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RTAPI_Message::clear_has_msglevel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RTAPI_Message::clear_msglevel() {
  msglevel_ = 0;
  clear_has_msglevel();
}
inline ::google::protobuf::int32 RTAPI_Message::msglevel() const {
  // @@protoc_insertion_point(field_get:machinetalk.RTAPI_Message.msglevel)
  return msglevel_;
}
inline void RTAPI_Message::set_msglevel(::google::protobuf::int32 value) {
  set_has_msglevel();
  msglevel_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.RTAPI_Message.msglevel)
}

// required string format = 20 [default = "*** uninitialized ***", (.nanopb) = {
inline bool RTAPI_Message::has_format() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RTAPI_Message::set_has_format() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RTAPI_Message::clear_has_format() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RTAPI_Message::clear_format() {
  format_.ClearToDefaultNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get());
  clear_has_format();
}
inline const ::std::string& RTAPI_Message::format() const {
  // @@protoc_insertion_point(field_get:machinetalk.RTAPI_Message.format)
  return format_.GetNoArena();
}
inline void RTAPI_Message::set_format(const ::std::string& value) {
  set_has_format();
  format_.SetNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get(), value);
  // @@protoc_insertion_point(field_set:machinetalk.RTAPI_Message.format)
}
#if LANG_CXX11
inline void RTAPI_Message::set_format(::std::string&& value) {
  set_has_format();
  format_.SetNoArena(
    &::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:machinetalk.RTAPI_Message.format)
}
#endif
inline void RTAPI_Message::set_format(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_format();
  format_.SetNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:machinetalk.RTAPI_Message.format)
}
inline void RTAPI_Message::set_format(const char* value, size_t size) {
  set_has_format();
  format_.SetNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:machinetalk.RTAPI_Message.format)
}
inline ::std::string* RTAPI_Message::mutable_format() {
  set_has_format();
  // @@protoc_insertion_point(field_mutable:machinetalk.RTAPI_Message.format)
  return format_.MutableNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get());
}
inline ::std::string* RTAPI_Message::release_format() {
  // @@protoc_insertion_point(field_release:machinetalk.RTAPI_Message.format)
  if (!has_format()) {
    return NULL;
  }
  clear_has_format();
  return format_.ReleaseNonDefaultNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get());
}
inline void RTAPI_Message::set_allocated_format(::std::string* format) {
  if (format != NULL) {
    set_has_format();
  } else {
    clear_has_format();
  }
  format_.SetAllocatedNoArena(&::machinetalk::RTAPI_Message::_i_give_permission_to_break_this_code_default_format_.get(), format);
  // @@protoc_insertion_point(field_set_allocated:machinetalk.RTAPI_Message.format)
}

// repeated .machinetalk.Value arg = 30 [(.nanopb) = {
inline int RTAPI_Message::arg_size() const {
  return arg_.size();
}
inline ::machinetalk::Value* RTAPI_Message::mutable_arg(int index) {
  // @@protoc_insertion_point(field_mutable:machinetalk.RTAPI_Message.arg)
  return arg_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::machinetalk::Value >*
RTAPI_Message::mutable_arg() {
  // @@protoc_insertion_point(field_mutable_list:machinetalk.RTAPI_Message.arg)
  return &arg_;
}
inline const ::machinetalk::Value& RTAPI_Message::arg(int index) const {
  // @@protoc_insertion_point(field_get:machinetalk.RTAPI_Message.arg)
  return arg_.Get(index);
}
inline ::machinetalk::Value* RTAPI_Message::add_arg() {
  // @@protoc_insertion_point(field_add:machinetalk.RTAPI_Message.arg)
  return arg_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::machinetalk::Value >&
RTAPI_Message::arg() const {
  // @@protoc_insertion_point(field_list:machinetalk.RTAPI_Message.arg)
  return arg_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace machinetalk

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_machinetalk_2fprotobuf_2frtapi_5fmessage_2eproto
